# 一,Exception

![image-20230108150800572](C:\Users\Alin\AppData\Roaming\Typora\typora-user-images\image-20230108150800572.png)

![image-20230108152014670](C:\Users\Alin\AppData\Roaming\Typora\typora-user-images\image-20230108152014670.png)..

## 一,Exception01 & 算数异常

```java
package com.exception_;

import sun.print.Win32MediaTray;

public class Exception01 {
    public static void main(String[] args) {
        int num1 = 10;
        int num2 = 0;
        /*1.由于分母为零,数学上是无穷,计算机上运行则会出错
        * 2.因此执行到这里为了能够使程序正常运行,则要抛出异常(ArithmeticException:算数异常)
        * 3.当抛出异常后,程序就退出,不执行下面代码
        *
        * 4.语法错误不是异常
        * 5.Error:java虚拟机无法解决的错误
        * 6.Exception:编程错误或偶然的外在因素导致的一般问题
        * eg:空指针访问,网络连接中断.....
        * 7.两大类异常:
        *       一,运行时异常(程序运行时发现的)
        *       二,编译时异常(编译器检测出来的)*/
        //int res = num1 / num2;
        /*可使用try-catch异常处理机制保证程序健壮性*/

        try {
            int res = num1 / num2;

        } catch (Exception e) {
            //e.printStackTrace();
            System.out.println(e.getMessage());//e.getMessage()把你的异常现象输出来
        }
        System.out.println("程序继续运行...");
    }
}
```



##  二,常见异常

```java
package com.exception_;

public class Exception02 {
    public static void main(String[] args) {
        //1.空指针异常NullPointerException
       /* String name = null;
        System.out.println(name.length());*/
        //2.数组越界异常ArrayIndexOutOfBoundsException
       /* int[] arr = {1,2,3};
        for (int i = 0; i <= arr.length; i++){//越界异常
            System.out.println(arr[i]);
        }*/

        //3.类型转换异常ClassCastException
        /*A b = new B();
        B b2 = (B)b;//这样可以
        try {
            C b3 = (C)b;//b的对象是B类型是A,虽然继承了A,但与C无关,所以类型转化异常
        } catch (ClassCastException e) {
            e.printStackTrace();
        }*/

        //4.数字格式异常NumberFormatException
       /* String name = "这里不写数字就会报数字格式异常";
        //将String 转换成 int
        int num = Integer.parseInt(name);*/
    }
}

//3.类型转换异常
class A {
}

class B extends A {
}

class C extends A {
}
```

![image-20230108154854295](C:\Users\Alin\AppData\Roaming\Typora\typora-user-images\image-20230108154854295.png).



## 三,异常处理练习

![image-20230108155438503](C:\Users\Alin\AppData\Roaming\Typora\typora-user-images\image-20230108155438503.png).



## 四,异常处理的方式

* #### try-catch-finally

1. ##### 程序员在代码中捕获发生的异常,自行处理

2. ![image-20230108160856440](C:\Users\Alin\AppData\Roaming\Typora\typora-user-images\image-20230108160856440.png).

* #### throws

1. ##### 将发生的异常抛出,交给 调用者(方法) 处理,最顶级的处理就是JVM

2. ![image-20230108162244224](C:\Users\Alin\AppData\Roaming\Typora\typora-user-images\image-20230108162244224.png).

## 五,Detail

### Detail01:

```java
package com.ExceptionDetail;

public class Detail01 {
    public static void main(String[] args) {
        /**
         * Detail:
         *  1.若异常发生,则一异常后面的代码不会执行,直接进入到catch块
         *  2.若无异常,则不执行catch
         *  3.若有无论发生异常都要执行的代码(eg:关闭连接,释放资源)
         *  则使用finally代码块
         */

        //t-c快捷键:ctrl + atl + t
        try {
            String str = "就就机甲";
            int a = Integer.parseInt(str);
            System.out.println("数字:" + a);
        } catch (NumberFormatException e) {
           System.out.println("异常输出:" + e.getMessage());
        }
        System.out.println("程序继续...");
    }
}
```





### Detail02:

```java
package com.ExceptionDetail;

public class Detail02 {
    public static void main(String[] args) {
        try {
            Person person = new Person();
            person = null;
            //Detail01再现:这里出错下面就不执行了
            System.out.println(person.getName());//NullPointer
            int n1 = 10;
            int n2 = 0;
            int res = n1 / n2;//Arithmetic

        }/*Detail02:要求 子类异常写在前 , 父类异常在后面*/
        catch (NullPointerException e){/*Detail02:可以用不同的catch捕获不同的异常(但不方便)*/
            System.out.println(e.getMessage());
        }
        catch (Exception e) {//Exception是NullPointer和Arithmetic的父类所以可以直接囊括两种异常
            System.out.println(e.getMessage());
        }
    }
}

class Person {
    private String name ="psda";

    public String getName() {
        return name;
    }
}
```

### Detail03:

```java
package com.ExceptionDetail;

public class Detail03 {
    public static void main(String[] args) {
        /**
         * t-f:没有捕获异常,程序会执行完finally后退出
         * 应用场景:
         *  执行一段代码,无论是否异常,都必须执行某个逻辑业务
          */
        try{
            int n1 = 10;
            int n2 = 0;
            System.out.println(n1 / n2);
        }finally {
            System.out.println("执行了finally....");
        }
        System.out.println("程序继续...");
    }
}
```

## 六,异常处理练习

1. ![image-20230108171446687](C:\Users\Alin\AppData\Roaming\Typora\typora-user-images\image-20230108171446687.png).
2. ![image-20230108171706805](C:\Users\Alin\AppData\Roaming\Typora\typora-user-images\image-20230108171706805.png).
3. ![image-20230108172258154](C:\Users\Alin\AppData\Roaming\Typora\typora-user-images\image-20230108172258154.png).

# 总结:

![image-20230108172431164](C:\Users\Alin\AppData\Roaming\Typora\typora-user-images\image-20230108172431164.png).

# <font color = "red">异常综合练习</font>.

## Excer01

```java
package com.Exercise;

import java.util.Scanner;

public class Excer01 {
    public static void main(String[] args) {
        /*若用户输入的不是一个整数,
        就提示他重新输入,直到输入一个整数*/
        input.method();
    }
}

class input {

    public static void method() {
        Scanner scanner = new Scanner(System.in);
        int res = 0;
        while (true) {
            System.out.println("请输入一个整数:");
            String num = scanner.next();
            try {
                res = Integer.parseInt(num);//执行到这里会自行判断是否为数字格式错误
                System.out.println("输入的整数为:" + res);
                break;
            } catch (NumberFormatException e) {
                System.out.println("输入的不是一个整数,重新输入..");
            }
        }
    }
}
```



# 二,Throws

![image-20230109125738137](C:\Users\Alin\AppData\Roaming\Typora\typora-user-images\image-20230109125738137.png).

![image-20230108162244224](C:\Users\Alin\AppData\Roaming\Typora\typora-user-images\image-20230108162244224.png).

## Detail01:

* #### 子类重写父类的方法时,子类抛出的异常等级要么跟父类一样要么比父类等级小否则会报错

![image-20230109130630111](C:\Users\Alin\AppData\Roaming\Typora\typora-user-images\image-20230109130630111.png).

## Detail 02:

* #### 运行异常,程序员<font color="orange">可不处理</font>,<font color="orange">默认交由JVM</font> 或者 <font color="orange">调用该异常的对象时程序员处理</font>.(拥有默认处理机制)

* #### 运行异常父类:<font color="orangere">RuntimeException</font>.

* #### 运行异常的子类(常用): 

  * #### <font color="orangere">(NullPointerException), (ArithmeticException) ,	(ArrayIndexOutOfBoundsException),	(ClassCastException),	(NumberFormatException)</font>.

* #### 编译异常: 程序员必须处理的  <font color="orangere">(FileNotFoundException) , (ClassNotFoundException)</font>.  

* 

* ```java
  package com.throws_;
  
  import java.io.FileInputStream;
  import java.io.FileNotFoundException;
  
  public class Throws01 {
      public static void main(String[] args) {
  
      }
      public void f1() throws FileNotFoundException,NullPointerException {//也可以写成Exception
          //创建一个文件流对象
          /*解析:
          *   1.这里的异常是FileNotFoundException 编译异常
          *   2.可使用t-c-f处理
          *   3.也可使用throws抛出异常到调用该方法的调用者
          *   4.throws关键字后可以抛出多个不同种类的异常*/
          FileInputStream fis = new FileInputStream("d://aa.txt");
      }
  }
  ```





# 三,自定义异常

* #### 步骤:

1. #### <font color="orange">定义类:自定义异常类名(自己写),继承Exception 或 RuntimeException</font>.

2. #### <font color="orange">若继承Exception,属于编译异常</font>.

3. #### <font color="orange">若继承RuntimeException,属于运行异常</font>.

### 自定义异常案例:

```java
package com.customException;
/*自定义异常案例:
*  1.接受一个Person对象年龄
*  2.要求:年龄范围在:18~120之间
* 3.不符合年龄范围标准的自定义一个异常
* (是继承RuntimeException的)*/
public class CustomException01 {
    public static void main(String[] args){/*默认了一个throws AgeException*/
        int age = 150;
        //要求年龄范围在:18~120之间否则抛出异常
        if (!(age >= 18 && age <= 120)){
            throw new AgeException("年龄不在反包围内");
        }
        System.out.println("年龄为:"+ age);
    }
}
//自定义一个异常
class AgeException extends RuntimeException{
    public AgeException(String message){//构造器
        super(message);
    }
}
/*解析:
* 1.一般我们都是用运行时异常
* 2.因为拥有默认异常处理机制,比较方便*/
```





### throw 与throws的区别

* ![image-20230109152426838](C:\Users\Alin\AppData\Roaming\Typora\typora-user-images\image-20230109152426838.png).

#### 测试题:

![image-20230109154430285](C:\Users\Alin\AppData\Roaming\Typora\typora-user-images\image-20230109154430285.png).



## HomeWork01:

```java
package com.HomeWork.Home01;
/*编程题:
 * 1.编写应用程序EcmDef.java,接收命令行的两个参数(整数),计算两数相除
 * 2.计算两个数相除,要求使用方法cal(int n1,int n2)
 * 3.对数据格式不正确(NumberFormatException),
 *   缺少命令行参数(ArrayIndexOutOfBoundsException),
 *   除0进行异常处理(ArithmeticException)*/
public class HomeWork01 {
    public static void main(String[] args) {
        try {
            //先验证输入的参数个数是否为俩(ArrayIndexOutOfBoundsException)
            if (args.length != 2){
                throw new ArrayIndexOutOfBoundsException("参数个数不对");
            }
            //先把接收的参数,转化成整数(NumberFormatException)
            int n1 = Integer.parseInt(args[0]);
            int n2 = Integer.parseInt(args[1]);

            double res = cal(n1,n2);//该方法可能抛出(ArithmeticException)
            System.out.println("计算结果:" + res);
        } catch (ArrayIndexOutOfBoundsException e) {
            System.out.println(e.getMessage());
        } catch (NumberFormatException e){
            System.out.println("参数格式不正确,需要输入整数数..");
        } catch (ArithmeticException e){
            System.out.println("出现除0异常..");
        }

    }
    /*2.计算俩数相除*/
    public static double cal(int n1,int n2){
        return n1 / n2;//可能报错(ArithmeticException)
    }
}
```



![image-20230109170536473](C:\Users\Alin\AppData\Roaming\Typora\typora-user-images\image-20230109170536473.png).



## HomeWork02:

![image-20230109172423965](C:\Users\Alin\AppData\Roaming\Typora\typora-user-images\image-20230109172423965.png).

## HomeWork03:

![image-20230118163605913](C:\Users\Alin\AppData\Roaming\Typora\typora-user-images\image-20230118163605913.png).